---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  
  
  
namespace: "trilium"
namePrefix: "trilium-"
images:
  - name: "zadam/trilium"
    newTag: "0.62.6"
  
  
configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
  
